### PR TITLE
Clarify how expired payments work

### PR DESCRIPTION
**Pull request by jonathanglassman**
https://payments-platform.atlassian.net/browse/PP-7245

### CODE REVIEW

**Comment by jonathanglassman** [comment]
@sfount, miriam suggested you're the man to work with on this

**Review by sfount — COMMENTED** [review]
This looks factually correct and clearer to me 👍  

Looking back at the Jira ticket, is there something we want to say about how the "authorisation" may be visible to user or look like "held" funds until the payment is either taken or cancelled/ expired?

How each card and bank deals with this can be different so I don't think we'd be able to say anything specific.

**Comment by jonathanglassman** [comment]
> This looks factually correct and clearer to me 👍
> 
> Looking back at the Jira ticket, is there something we want to say about how the "authorisation" may be visible to user or look like "held" funds until the payment is either taken or cancelled/ expired?
> 
> How each card and bank deals with this can be different so I don't think we'd be able to say anything specific.

@sfount How about the latest amend?

**Review by sfount — APPROVED** [review]
Nice one, looks good 👍

**Pull request merged**
