### PR TITLE
adds warning symbol 

### PR DESCRIPTION
**Pull request by bahmady**
### Context
Adds Design System components and a warning symbol to prove it works (it's appropriate to have one here rather than a blockquote, as we're currently using), in the payment flow section 

### Changes proposed in this pull request
Follows https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-from-dist.md

### Guidance to review
https://govukpay-designsystem.cloudapps.digital/payment_flow_overview/#payment-flow

### CODE REVIEW

**Comment by bahmady** [comment]
Thanks @jonheslop that makes a lot of sense. I ran it by another dev and he said he thinks it should go in https://github.com/alphagov/tech-docs-gem/blob/master/lib/source/layouts/core.erb

If you have any time to go through how to do it that would be awesome

**Comment by bahmady** [comment]
@jonheslop this may also be of interest https://github.com/alphagov/tech-docs-gem/pull/34

**Comment by bahmady** [comment]
Well it seems to still work without the `<html>` and `<body>` content (per latest commit https://github.com/alphagov/pay-tech-docs/pull/200/commits/31508f59f70a45be83230098f3f3913af5d5e79e) but I can't solve the updating problem.

**Comment by jonheslop** [comment]
Yeah both ways will work, but you’re pulling in the css for the whole design system just for one componenent from it which seems wasteful.

I think you could remove everything an just leave in the markup for the warning text and include this just above it

```html
<style>
.govuk-warning-text{font-family:nta,Arial,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-weight:400;font-size:16px;font-size:1rem;line-height:1.25;color:#0b0c0c;position:relative;margin-bottom:20px;padding:10px 0}@media print{.govuk-warning-text{font-family:sans-serif}}@media (min-width:40.0625em){.govuk-warning-text{font-size:19px;font-size:1.1875rem;line-height:1.31579}}@media print{.govuk-warning-text{font-size:14pt;line-height:1.15;color:#000}}@media (min-width:40.0625em){.govuk-warning-text{margin-bottom:30px}}.govuk-warning-text__assistive{position:absolute!important;width:1px!important;height:1px!important;margin:-1px!important;padding:0!important;overflow:hidden!important;clip:rect(0 0 0 0)!important;-webkit-clip-path:inset(50%)!important;clip-path:inset(50%)!important;border:0!important;white-space:nowrap!important}.govuk-warning-text__icon{font-family:nta,Arial,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-weight:700;display:inline-block;position:absolute;top:50%;left:0;min-width:32px;min-height:29px;margin-top:-20px;padding-top:3px;border:3px solid #0b0c0c;border-radius:50%;color:#fff;background:#0b0c0c;font-size:1.6em;line-height:29px;text-align:center;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}@media print{.govuk-warning-text__icon{font-family:sans-serif}}.govuk-warning-text__text{display:block;margin-left:-15px;padding-left:65px}
</style>
```

**Comment by bahmady** [comment]
Oooh that works! Thanks @jonheslop : presumably it's secure to do it this way?

**Comment by jonheslop** [comment]
Yeah totally fine

**Comment by bahmady** [comment]
image

Do I have to put the `<style>` content in the same file each time or is there somewhere sensible/central I can put it?

**Comment by jonheslop** [comment]
I can’t see anywhere or see anything obvious from the docs, but there probably is a way, on `pay-product-page` which is similar we have this file — https://github.com/alphagov/pay-product-page/blob/master/source/layouts/layout.erb which is where we would put it. Is there someone you can ask with more context of `govuk-tech-docs`

**Comment by bahmady** [comment]
It works if I put it in this file (in a fork): https://github.com/alphagov/tech-docs-gem/blob/master/lib/source/layouts/core.erb

But I need to use the proper one so I'm just going to put it inside the actual Markdown file, I think. 

Thanks again Jon 👍

**Comment by bahmady** [comment]
I've revamped this PR to just include @jonheslop 's simple, great solution

**Pull request merged**
