### PR TITLE
Add reference step to set up selfservice payment

### PR DESCRIPTION
**Pull request by soniaturcotte**

### CODE REVIEW

**Comment by soniaturcotte** [comment]
@bahmady I tried to copy the style of the previous steps, but please change if it doesn't meet the style guide or you think that it could be clearer.

**Comment by jonathanglassman** [comment]
@soniaturcotte thanks for doing this. My query is what actually happens in the first step - do you complete a field, or if you want it created for you do you select a "create reference number" button?

**Comment by jonathanglassman** [comment]
Also, I think we need to change 

"Create a payment link
1. Sign in to your GOV.UK Pay account.
2. Select Create a payment link in the Dashboard."

to

"Create a payment link
Sign in to your GOV.UK Pay account.
Select Create and manage payment links in the Dashboard."

**Comment by jonathanglassman** [comment]
I've made a couple of changes based on going through creating a payment link. Let me know what you think.

**Comment by bahmady** [comment]
@soniaturcotte shall I merge this? are the Pay docs deployed manually or by CI?

**Comment by soniaturcotte** [comment]
We have CI, I've merged. Thanks both!

**Pull request merged**
