### PR TITLE
[WIP] Fact-check-a-thon - Digital Wallets

### PR DESCRIPTION
**Pull request by jonathanglassman**
Add into docs that we don’t pass on cardholder details unless those details are collected in the service

### CODE REVIEW

**Comment by jonathanglassman** [comment]
@stevenjmesser, a couple of questions:

- Who do we not pass cardholder information to?
- "unless that information is collected in the service" - as in, collected as part of the service the cardholder uses?

**Comment by stevenjmesser** [comment]
Hey @jonathanglassman!

When a payment is made using a digital wallet, the transfer of card details happens between Apple/Google Pay and the payment service provider. Usually cardholder information passes through our systems to allow the payment service provider to authorise the payment, but since we don't see it for digital wallet transactions we're unable to pass it on.

If a service is using the cardholder's billing address as part of the service, ideally they'll need to collect this within the service transaction but not through Pay, as we can't collect users' data that isn't for the purposes of initiating a payment. Collecting users' details for another purpose would widen the scope (and risk) of data we collect and hold for services. 

Hopefully that's clear but let me know if you have any questions!

**Comment by jonathanglassman** [comment]
> Hey @jonathanglassman!
> 
> When a payment is made using a digital wallet, the transfer of card details happens between Apple/Google Pay and the payment service provider. Usually cardholder information passes through our systems to allow the payment service provider to authorise the payment, but since we don't see it for digital wallet transactions we're unable to pass it on.
> 
> If a service is using the cardholder's billing address as part of the service, ideally they'll need to collect this within the service transaction but not through Pay, as we can't collect users' data that isn't for the purposes of initiating a payment. Collecting users' details for another purpose would widen the scope (and risk) of data we collect and hold for services.
> 
> Hopefully that's clear but let me know if you have any questions!

thanks @stevenjmesser, i've redrafted, PTAL when you can

**Comment by stevenjmesser** [comment]
Forgive me, what does PTAL stand for?

**Comment by jonathanglassman** [comment]
> Forgive me, what does PTAL stand for?

Sorry. Please Take A Look.

**Comment by stevenjmesser** [comment]
Ta. Looks good to me!

**Review by stevenjmesser — APPROVED** [review]

**Comment by jonathanglassman** [comment]
thank you!

**Pull request merged**
